"use strict"
function headerUI(){
	return '<header id="header">'
	+'<div class="container main-menu">'
		+'<div class="row align-items-center justify-content-between d-flex">'
			+'<div id="logo">'
				+'<a href="index.html">'
				+'<img src="'+$.ctx()+'/resources/img/logo.png" alt="" title="" /></a>'
			+'</div>'
			+'<nav id="nav-menu-container">'
				+'<ul class="nav-menu">'
					+'<li><a>Home</a></li>'
					+'<li><a id="logout_btn">로그아웃</a></li>'
					+'<li><a id="join_btn">마이페이지</a></li>'
					+'<li><a href="portfolio.html">검색</a></li>'
					+'<li><a href="price.html">Pricing</a></li>'
					+'<li class="menu-has-children"><a href="">Blog</a>'
						+'<ul>'
							+'<li><a href="blog-home.html">Blog Home</a></li>'
							+'<li><a href="blog-single.html">Blog Single</a></li>'
						+'</ul></li>'
					+'<li id="my_board" class="menu-has-children"><a>게시판</a>'
						+'<ul>'
							+'<li><a id="board_write">게시글 쓰기</a></li>'
							+'<li><a id="board_list">게시글 목록보기</a></li>'
							+'<li class="menu-has-children"><a href="">Level 2 </a>'
								+'<ul>'
									+'<li><a href="#">Item One</a></li>'
									+'<li><a href="#">Item Two</a></li>'
								+'</ul></li>'
						+'</ul></li>'
					+'<li><a href="contact.html">Contact</a></li>'
				+'</ul>'
			+'</nav>'
			+'<!-- #nav-menu-container -->'
		+'</div>'
	+'</div>'
+'</header>';
}

